/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/app/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        lightgrey: '#d0d6d6',
        mint: '#86b9b0',
        turquoise: '#4c7273',
        darkteal: '#042630',
        deepblue: '#041421',
        gray: '#626363',
        verydarkgreen: '#021302',
        quitedarkgreen: '#012202',
        darkgreen: '#034504',
        green: '#046206',
        lightgreen: '#008501',
        verylightgreen: '#AAFA92',
      },
      fontFamily: {
        montserrat_black: ['montserrat_black'],
        montserrat_blackitalic: ['montserrat_blackitalic'],
        montserrat_bold: ['montserrat_bold'],
        montserrat_bolditalic: ['montserrat_bolditalic'],
        montserrat_extrabold: ['montserrat_extrabold'],
        montserrat_extrabolditalic: ['montserrat_extrabolditalic'],
        montserrat_extralight: ['montserrat_extralight'],
        montserrat_extralightitalic: ['montserrat_extralightitalic'],
        montserrat_italic: ['montserrat_italic'],
        montserrat_light: ['montserrat_light'],
        montserrat_lightitalic: ['montserrat_lightitalic'],
        montserrat_medium: ['montserrat_medium'],
        montserrat_mediumitalic: ['montserrat_mediumitalic'],
        montserrat_regular: ['montserrat_regular'],
        montserrat_semibold: ['montserrat_semibold'],
        montserrat_semibolditalic: ['montserrat_semibolditalic'],
        montserrat_thin: ['montserrat_thin'],
        montserrat_thinitalic: ['montserrat_thinitalic'],
      },
    },
  },
  plugins: [],
}

